### ISSUE TITLE
unable to access admin part  

### ISSUE THREAD

**Issue by rameshreddyvemula** [rappasoft/vault#15]
access/users url redirecting to dashboard. i used laravel-5-boilerplate and vault package, i didn't found any errors at time of installation but am unable access admin part, all Role and Permissions of Controllers and Middleware files are at Vendor only

**Comment by NeDetto** [comment]
I think you see this because you are not logged in as administrator.
Try this: 
- go to yourtestarea.app:8000/auth/login
- login as admin (if you "migrate and seed table" this is the account "admin@admin.com" and password i don't know. i generate new password for my testcase).
- after this go to yourtestarea.app:8000/access/users

With this method, i can enter in the Route correctly

**Comment by rappasoft** [comment]
Yes it will obviously only allow access if you are logged in as the default admin. Make sure you run the seeder, after doing so you can change the admin password from the backend.
