### ISSUE TITLE
permission_role allows for multiple repeating entries

### ISSUE THREAD

**Issue by makstr** [rappasoft/vault#7]
![screen shot 2015-02-09 at 13 18 41](https://cloud.githubusercontent.com/assets/10668265/6106065/69644d72-b05e-11e4-9623-c5b817e5d7da.png)

**Comment by rappasoft** [comment]
@petewwa what steps are you taking to get the above result so I can trace through the source?

**Comment by makstr** [comment]
I just got started and this occurs randomly. I followed your VaultTableSeeder and created some permissions and roles of my own. Then when I tried to manipulate them via the browser I received strange results such as administrator role having the View Administrator Link attached to it 3 times

```
    $permission_model = Config::get('vault.permission');
        $flyAbove = new $permission_model;
        $flyAbove->name = 'fly_above_the_ground';
        $flyAbove->display_name = 'Fly above the ground';
        $flyAbove->system = true;
        $flyAbove->created_at = \Carbon\Carbon::now();
        $flyAbove->updated_at = \Carbon\Carbon::now();
        $flyAbove->save();


        $rolePrototyper = new $role_model;
        $rolePrototyper->name = 'Prototyper';
        $rolePrototyper->created_at = \Carbon\Carbon::now();
        $rolePrototyper->updated_at = \Carbon\Carbon::now();
        $rolePrototyper->save();
        $rolePrototyper->attachPermission($flyAbove);

        $user_model = Config::get('auth.model');
        $user_model::first()->attachRole($rolePrototyper);

```

**Comment by makstr** [comment]
By the way what purpose does the "system" attribute in permission model have?

**Comment by rappasoft** [comment]
System is just a flag, it takes away the delete button on the UI so you don't accidentally delete it if it's really important.

**Comment by rappasoft** [comment]
Also, can you try to wipe everything, run the seed once, then use the UI to add your roles and permissions? The seeder isn't going to do many checks when using it, however the CRUD operations on the UI should prevent it from doing the above, if it isn't then theres a bug that needs to be fixed. However, the above won't crash your application because the code will still see that it exists and perform the right operations, it's just annoying and shouldn't be doing that if it is. But try this first.

**Comment by rappasoft** [comment]
Have you tried the above?
